const en = {
  title: "Files & artifacts",
  close: "Close files",
  directory: "Authorized directory",
  authorize: "Authorize directories in desktop Web settings.",
  views: "File views",
  artifacts: "Task artifacts",
  files: "Project files",
  diff: "Changes",
  refresh: "Refresh",
  diffNote: "Current repository changes; these may include your own edits.",
  diffKind: "Diff kind",
  worktree: "Working tree",
  staged: "Staged",
  commit: "Commit",
  commitSha: "Commit SHA",
  view: "View",
  partial: "Binary, submodule or truncated content may not be fully displayed.",
  noChanges: "No text changes",
  noDiff: "No repository diff available",
  loading: "Loading…",
  parent: "Parent directory",
  empty: "No files in this view",
  earlier: "Earlier references",
  back: "Back to list",
  prepareDownload: "Prepare download",
  download: "Download",
  open: "Open / download",
  mediaError: "Media unavailable or codec unsupported; try downloading.",
  expired: "Preview expired. Open the file again.",
  changed: "File changed. Open it again.",
  denied: "File access is not authorized.",
  loadError: "Unable to load this file. Try again.",
};
type Copy = typeof en;
const zh: Copy = {
  title: "文件与产物",
  close: "关闭文件面板",
  directory: "已授权目录",
  authorize: "请在桌面 Web 设置中授权目录。",
  views: "文件视图",
  artifacts: "会话产物",
  files: "项目文件",
  diff: "变更",
  refresh: "刷新",
  diffNote: "当前仓库差异，可能包含你已有的修改，不代表全部由该会话生成。",
  diffKind: "差异类型",
  worktree: "工作区",
  staged: "暂存区",
  commit: "提交",
  commitSha: "提交 SHA",
  view: "查看",
  partial: "二进制、子模块或截断内容可能无法完整显示。",
  noChanges: "无文本差异",
  noDiff: "没有可读取的仓库差异",
  loading: "正在读取…",
  parent: "上级目录",
  empty: "当前没有文件",
  earlier: "读取更早的文件引用",
  back: "返回列表",
  prepareDownload: "获取下载链接",
  download: "下载",
  open: "打开 / 下载",
  mediaError: "媒体不可用或编码不受支持，可尝试下载。",
  expired: "预览已过期，请重新打开文件。",
  changed: "文件已更新，请重新打开。",
  denied: "尚未获得该文件的访问权限。",
  loadError: "无法读取该文件，请重试。",
};
const tw: Copy = {
  title: "檔案與產物",
  close: "關閉檔案面板",
  directory: "已授權目錄",
  authorize: "請在桌面 Web 設定中授權目錄。",
  views: "檔案檢視",
  artifacts: "對話產物",
  files: "專案檔案",
  diff: "變更",
  refresh: "重新整理",
  diffNote: "目前儲存庫差異可能包含你已有的修改，不代表全部由此對話產生。",
  diffKind: "差異類型",
  worktree: "工作區",
  staged: "暫存區",
  commit: "提交",
  commitSha: "提交 SHA",
  view: "檢視",
  partial: "二進位、子模組或截斷內容可能無法完整顯示。",
  noChanges: "無文字差異",
  noDiff: "沒有可讀取的儲存庫差異",
  loading: "正在讀取…",
  parent: "上層目錄",
  empty: "目前沒有檔案",
  earlier: "讀取較早的檔案引用",
  back: "返回清單",
  prepareDownload: "取得下載連結",
  download: "下載",
  open: "開啟 / 下載",
  mediaError: "媒體無法使用或編碼不受支援，可嘗試下載。",
  expired: "預覽已過期，請重新開啟檔案。",
  changed: "檔案已更新，請重新開啟。",
  denied: "尚未取得該檔案的存取權限。",
  loadError: "無法讀取該檔案，請重試。",
};
const ja: Copy = {
  title: "ファイルと成果物",
  close: "ファイルパネルを閉じる",
  directory: "許可済みディレクトリ",
  authorize: "デスクトップの Web 設定でディレクトリを許可してください。",
  views: "ファイル表示",
  artifacts: "会話の成果物",
  files: "プロジェクトファイル",
  diff: "変更",
  refresh: "更新",
  diffNote: "現在のリポジトリの差分です。会話以外で行われた変更も含まれる場合があります。",
  diffKind: "差分の種類",
  worktree: "作業ツリー",
  staged: "ステージ済み",
  commit: "コミット",
  commitSha: "コミット SHA",
  view: "表示",
  partial: "バイナリ、サブモジュール、省略された内容は完全に表示できない場合があります。",
  noChanges: "テキストの変更はありません",
  noDiff: "表示できる差分がありません",
  loading: "読み込み中…",
  parent: "親ディレクトリ",
  empty: "ファイルがありません",
  earlier: "以前のファイル参照",
  back: "一覧に戻る",
  prepareDownload: "ダウンロードリンクを取得",
  download: "ダウンロード",
  open: "開く / ダウンロード",
  mediaError: "メディアまたは形式を再生できません。ダウンロードをお試しください。",
  expired: "プレビューの期限が切れました。ファイルを開き直してください。",
  changed: "ファイルが更新されました。開き直してください。",
  denied: "ファイルへのアクセスが許可されていません。",
  loadError: "ファイルを読み込めません。再試行してください。",
};
export function artifactCopy(locale: string): Copy {
  return locale === "en-US" ? en : locale === "zh-TW" ? tw : locale === "ja-JP" ? ja : zh;
}
