export const remoteAccountCopy = {
  "zh-CN": {
    title: "远控账号",
    intro: "账号仅用于公网远控的设备登记与管理。本地会话和 Codex 无需登录。",
    loading: "正在读取账号状态…",
    signedOut: "未登录",
    login: "在浏览器中登录或注册",
    cancel: "取消登录",
    signingIn: "请在系统浏览器中完成登录。登录成功后，仍需手动开启远程访问。",
    manage: "管理账号",
    logout: "退出并暂停公网远控",
    logoutHint:
      "退出保留设备归属和手机授权，本地 Codex 任务继续运行。重新登录原账号后，可手动恢复公网访问。",
    claim: "将这台电脑绑定到当前账号",
    unclaimed:
      "这台电脑尚未绑定账号。绑定会暂停公网访问，并保留连接地址和已有手机授权；成功后请手动恢复。",
    owned: "这台电脑已绑定当前账号",
    other: "这台电脑属于其他账号，请登录原账号。",
    quota: "已登记设备",
    totp: "两步验证",
    on: "已开启",
    off: "未开启，可在账号管理中设置",
    unavailable: "账号服务暂不可用，请稍后重试。",
    retry: "重试",
    storage: "系统安全存储不可用，无法保存登录凭据。请先恢复系统钥匙串或凭据存储。",
    failed: "操作未完成，请重试。",
    expired: "登录已失效，请重新登录。",
    timeout: "浏览器登录已超时，请重新开始。",
    conflict: "电脑已归属其他账号，无法绑定。",
    limit: "账号设备数已达上限，请先在账号管理中撤销不再使用的设备。",
    revokeFailed:
      "已在本机退出并暂停公网远控，但未能确认服务器上的登录会话已撤销。请在账号管理中检查并撤销该登录会话。",
    suspended: "账号当前不可用，请在账号管理中检查状态。",
    claimPending: "设备绑定结果待核对，公网访问保持暂停。请重新登录原账号进行核对。",
    profileFailed: "账号状态暂未刷新，请重试核对设备配额。",
  },
  "zh-TW": {
    title: "遠端帳號",
    intro: "帳號僅用於公網遠端存取的裝置登記與管理。本機對話和 Codex 無需登入。",
    loading: "正在讀取帳號狀態…",
    signedOut: "未登入",
    login: "在瀏覽器中登入或註冊",
    cancel: "取消登入",
    signingIn: "請在系統瀏覽器中完成登入。登入成功後，仍需手動啟用遠端存取。",
    manage: "管理帳號",
    logout: "登出並暫停公網遠端存取",
    logoutHint:
      "登出保留裝置歸屬和手機授權，本機 Codex 任務繼續執行。重新登入原帳號後，可手動恢復公網存取。",
    claim: "將這台電腦綁定至目前帳號",
    unclaimed:
      "這台電腦尚未綁定帳號。綁定會暫停公網存取，並保留連線位址和既有手機授權；成功後請手動恢復。",
    owned: "這台電腦已綁定目前帳號",
    other: "這台電腦屬於其他帳號，請登入原帳號。",
    quota: "已登記裝置",
    totp: "兩步驟驗證",
    on: "已啟用",
    off: "未啟用，可在帳號管理中設定",
    unavailable: "帳號服務暫時無法使用，請稍後重試。",
    retry: "重試",
    storage: "系統安全儲存無法使用，無法儲存登入憑證。請先恢復系統鑰匙圈或認證儲存。",
    failed: "操作未完成，請重試。",
    expired: "登入已失效，請重新登入。",
    timeout: "瀏覽器登入已逾時，請重新開始。",
    conflict: "電腦已屬於其他帳號，無法綁定。",
    limit: "帳號裝置數已達上限，請先在帳號管理中撤銷不再使用的裝置。",
    revokeFailed:
      "已在本機登出並暫停公網遠端存取，但無法確認伺服器上的登入工作階段已撤銷。請在帳號管理中檢查並撤銷該登入工作階段。",
    suspended: "帳號目前無法使用，請在帳號管理中檢查狀態。",
    claimPending: "裝置綁定結果待核對，公網存取保持暫停。請重新登入原帳號核對。",
    profileFailed: "帳號狀態尚未更新，請重試核對裝置配額。",
  },
  "en-US": {
    title: "Remote account",
    intro:
      "Your account registers and manages computers for public remote access. Local conversations and Codex do not require sign-in.",
    loading: "Loading account status…",
    signedOut: "Signed out",
    login: "Sign in or register in browser",
    cancel: "Cancel sign-in",
    signingIn:
      "Finish signing in in your system browser. Enable remote access manually after signing in.",
    manage: "Manage account",
    logout: "Sign out and pause public access",
    logoutHint:
      "Signing out preserves computer ownership and browser grants. Local Codex tasks keep running. Sign in to the original account to enable public access again.",
    claim: "Link this computer to this account",
    unclaimed:
      "This computer is not linked to an account. Linking pauses public access and preserves its address and browser grants. Enable access again after linking.",
    owned: "This computer is linked to this account",
    other: "This computer belongs to another account. Sign in to the original account.",
    quota: "Registered computers",
    totp: "Two-step verification",
    on: "Enabled",
    off: "Not enabled; configure in account management",
    unavailable: "Account service is unavailable. Try again later.",
    retry: "Retry",
    storage:
      "Secure system storage is unavailable. Restore your system keychain or credential store before saving sign-in credentials.",
    failed: "The operation did not complete. Try again.",
    expired: "Your sign-in has expired. Sign in again.",
    timeout: "Browser sign-in timed out. Start again.",
    conflict: "This computer already belongs to another account and cannot be linked.",
    limit:
      "Your computer limit has been reached. Revoke an unused computer in account management first.",
    revokeFailed:
      "Signed out locally and paused public access, but server session revocation could not be confirmed. Check and revoke this sign-in session in account management.",
    suspended: "This account is unavailable. Check its status in account management.",
    claimPending:
      "Computer linking needs verification. Public access remains paused. Sign in to the original account again to verify it.",
    profileFailed: "Account status could not be refreshed. Retry to check the computer quota.",
  },
  "ja-JP": {
    title: "リモートアカウント",
    intro:
      "アカウントは公衆ネットワーク経由のリモート接続の端末登録と管理にのみ使用します。ローカルの会話や Codex にログインは不要です。",
    loading: "アカウントの状態を読み込み中…",
    signedOut: "未ログイン",
    login: "ブラウザーでログイン・登録",
    cancel: "ログインをキャンセル",
    signingIn:
      "システムブラウザーでログインしてください。ログイン後、リモートアクセスを手動で有効にします。",
    manage: "アカウントを管理",
    logout: "ログアウトして公衆接続を一時停止",
    logoutHint:
      "端末の所属とブラウザーの認証は保持され、ローカルの Codex タスクは続行します。元のアカウントにログインし、手動で接続を再開できます。",
    claim: "このパソコンを現在のアカウントに登録",
    unclaimed:
      "このパソコンはアカウントに未登録です。登録時に公衆接続を一時停止し、接続先と既存のブラウザー認証は保持します。登録後は手動で再開してください。",
    owned: "このパソコンは現在のアカウントに登録済みです",
    other: "このパソコンは別のアカウントに属しています。元のアカウントにログインしてください。",
    quota: "登録済み端末",
    totp: "2段階認証",
    on: "有効",
    off: "未設定。アカウント管理で設定できます",
    unavailable: "アカウントサービスを利用できません。後でもう一度お試しください。",
    retry: "再試行",
    storage:
      "システムの安全なストレージを利用できません。キーチェーンまたは資格情報ストアを復旧してください。",
    failed: "操作が完了しませんでした。再試行してください。",
    expired: "ログインの有効期限が切れました。再度ログインしてください。",
    timeout: "ブラウザーでのログインがタイムアウトしました。やり直してください。",
    conflict: "このパソコンは既に別のアカウントに属しているため登録できません。",
    limit: "登録端末数の上限に達しています。アカウント管理で未使用の端末を解除してください。",
    revokeFailed:
      "ローカルでログアウトし公衆接続を停止しましたが、サーバーのログインセッションの失効は確認できませんでした。アカウント管理で確認して解除してください。",
    suspended: "現在このアカウントを利用できません。アカウント管理で状態を確認してください。",
    claimPending:
      "端末登録の結果を確認する必要があります。公衆接続は停止中です。元のアカウントに再ログインして確認してください。",
    profileFailed: "アカウント状態を更新できませんでした。再試行して端末数を確認してください。",
  },
};
