export const webSettingsCopy = {
  "zh-CN": {
    acceptance: "本地隔离验收模式：控制仅限以下会话，不代表正式验收通过。",
    portError: "端口已被占用，请选择其他端口后保存。",
    unverified: "本构建尚未通过 Web 实验控制真实验收，发送与审批保持禁用。",
    title: "Web 访问",
    enabled: "启用本机 Web 服务",
    port: "端口",
    origin: "外部 HTTPS 地址",
    experimental: "启用实验控制（仍需分别授予浏览器权限）",
    save: "保存设置",
    generate: "生成八位配对码",
    scope:
      "授权包含全部已登记及以后新增的工作区。远程访问请自行配置 HTTPS 反向代理或隧道；桌面应用必须保持运行。",
    pending: "待确认浏览器",
    devices: "已授权浏览器",
    verify: "请与浏览器核对校验数字",
    send: "允许发送",
    approve: "允许审批",
    accept: "确认授权",
    reject: "拒绝",
    revoke: "撤销",
    empty: "暂无",
    running: "运行中",
    stopped: "已关闭",
    expires: "有效期至",
    loading: "正在读取 Web 设置…",
    unavailable: "Web 设置不可用",
    warning: "实验功能仅在通过验证的主机与会话上可用；不提供停止功能。",
    read: "历史读取",
  },
  "zh-TW": {
    acceptance: "本機隔離驗收模式：操作僅限以下對話，不代表正式驗收通過。",
    portError: "連接埠已被佔用，請選擇其他連接埠後儲存。",
    unverified: "此建置尚未通過 Web 實驗控制真實驗收，傳送與核准維持停用。",
    title: "Web 存取",
    enabled: "啟用本機 Web 服務",
    port: "連接埠",
    origin: "外部 HTTPS 位址",
    experimental: "啟用實驗控制（仍需分別授予瀏覽器權限）",
    save: "儲存設定",
    generate: "產生八位配對碼",
    scope:
      "授權包含全部已登記及以後新增的工作區。遠端存取請自行設定 HTTPS 反向代理或隧道；桌面應用程式必須保持執行。",
    pending: "待確認瀏覽器",
    devices: "已授權瀏覽器",
    verify: "請與瀏覽器核對驗證數字",
    send: "允許傳送",
    approve: "允許核准",
    accept: "確認授權",
    reject: "拒絕",
    revoke: "撤銷",
    empty: "暫無",
    running: "執行中",
    stopped: "已關閉",
    expires: "有效期限",
    loading: "正在讀取 Web 設定…",
    unavailable: "Web 設定無法使用",
    warning: "實驗功能僅在通過驗證的主機與對話上可用；不提供停止功能。",
    read: "歷史讀取",
  },
  "en-US": {
    acceptance:
      "Isolated local acceptance: controls are limited to this session. This is not release approval.",
    portError: "This port is in use. Choose another port and save.",
    unverified:
      "Web experimental controls have not passed live acceptance in this build. Sending and approvals remain disabled.",
    title: "Web access",
    enabled: "Enable local Web service",
    port: "Port",
    origin: "External HTTPS origin",
    experimental: "Enable experimental controls (browser grants are still required)",
    save: "Save settings",
    generate: "Generate 8-digit pairing code",
    scope:
      "Access includes every registered workspace, including future additions. Configure your own HTTPS reverse proxy or tunnel for remote access. Keep the desktop application running.",
    pending: "Pending browsers",
    devices: "Authorized browsers",
    verify: "Compare these verification digits with the browser",
    send: "Allow sending",
    approve: "Allow approvals",
    accept: "Authorize",
    reject: "Reject",
    revoke: "Revoke",
    empty: "None",
    running: "Running",
    stopped: "Disabled",
    expires: "Expires",
    loading: "Loading Web settings…",
    unavailable: "Web settings unavailable",
    warning:
      "Experimental controls require a verified host and session. Stopping is not supported.",
    read: "Read history",
  },
  "ja-JP": {
    acceptance:
      "ローカル検証モード：操作は次のセッションのみ対象です。正式な検証完了ではありません。",
    portError: "ポートは使用中です。別のポートを選択して保存してください。",
    unverified: "このビルドの Web 操作は実環境で未検証のため、送信と承認は無効です。",
    title: "Web アクセス",
    enabled: "ローカル Web サービスを有効化",
    port: "ポート",
    origin: "外部 HTTPS アドレス",
    experimental: "実験的な操作を有効化（ブラウザーごとの権限も必要）",
    save: "設定を保存",
    generate: "8 桁のペアリングコードを生成",
    scope:
      "登録済みおよび今後追加されるすべてのワークスペースが対象です。リモートアクセスには独自の HTTPS リバースプロキシまたはトンネルを設定し、デスクトップアプリを起動したままにしてください。",
    pending: "確認待ちのブラウザー",
    devices: "認証済みブラウザー",
    verify: "ブラウザーに表示された確認番号と照合してください",
    send: "送信を許可",
    approve: "承認操作を許可",
    accept: "アクセスを許可",
    reject: "拒否",
    revoke: "取り消す",
    empty: "なし",
    running: "稼働中",
    stopped: "無効",
    expires: "有効期限",
    loading: "Web 設定を読み込み中…",
    unavailable: "Web 設定を利用できません",
    warning: "実験的な操作は検証済みのホストと会話のみで利用できます。停止機能はありません。",
    read: "履歴の閲覧",
  },
};
