import type { Locale } from "@/i18n";
export const catalogCopy = {
  "zh-CN": {
    options: "目录选项",
    agent: "Agent",
    allAgents: "全部 Agent",
    records: "记录类型",
    current: "当前",
    archived: "归档",
    metadata: "仅元数据",
    all: "全部",
    auxiliary: "显示辅助会话",
    missing: "项目信息不可用，请升级桌面端",
    noResults: "没有匹配的会话",
    project: "项目",
    path: "完整路径",
    updated: "更新时间",
    created: "创建时间",
    branch: "分支",
    branchAtCreation: "创建时分支",
    executionDirectory: "Codex 执行目录",
    codexProjectId: "Codex 项目 ID",
    contextLoading: "正在读取 Codex 信息…",
    contextUnavailable: "Codex 信息不可用",
    codexContextNote:
      "这里显示 Codex 原生线程信息。当前无法在手机端创建 Codex 工作树或指定起始分支；目录路径不代表工作树类型。",
    fork: "分叉自",
    spawned: "派生自",
    unknown: "未知",
    source: "来源",
    interactive: "交互会话",
    auxiliarySource: "辅助会话",
  },
  "zh-TW": {
    options: "目錄選項",
    agent: "Agent",
    allAgents: "全部 Agent",
    records: "記錄類型",
    current: "目前",
    archived: "封存",
    metadata: "僅中繼資料",
    all: "全部",
    auxiliary: "顯示輔助會話",
    missing: "專案資訊不可用，請升級桌面端",
    noResults: "沒有符合的會話",
    project: "專案",
    path: "完整路徑",
    updated: "更新時間",
    created: "建立時間",
    branch: "分支",
    branchAtCreation: "建立時分支",
    executionDirectory: "Codex 執行目錄",
    codexProjectId: "Codex 專案 ID",
    contextLoading: "正在讀取 Codex 資訊…",
    contextUnavailable: "Codex 資訊無法取得",
    codexContextNote:
      "這裡顯示 Codex 原生工作階段資訊。目前無法在手機建立 Codex 工作樹或指定起始分支；目錄路徑不代表工作樹類型。",
    fork: "分叉自",
    spawned: "衍生自",
    unknown: "未知",
    source: "來源",
    interactive: "互動會話",
    auxiliarySource: "輔助會話",
  },
  "en-US": {
    options: "Catalog options",
    agent: "Agent",
    allAgents: "All Agents",
    records: "Record type",
    current: "Current",
    archived: "Archived",
    metadata: "Metadata only",
    all: "All",
    auxiliary: "Show auxiliary sessions",
    missing: "Project information unavailable. Upgrade the desktop app.",
    noResults: "No matching sessions",
    project: "Project",
    path: "Full path",
    updated: "Updated",
    created: "Created",
    branch: "Branch",
    branchAtCreation: "Branch at creation",
    executionDirectory: "Codex working directory",
    codexProjectId: "Codex project ID",
    contextLoading: "Reading Codex details…",
    contextUnavailable: "Codex details unavailable",
    codexContextNote:
      "These details come from the native Codex thread. Creating a Codex worktree or choosing a starting branch from your phone is not available yet; a directory path does not identify a worktree type.",
    fork: "Forked from",
    spawned: "Spawned from",
    unknown: "Unknown",
    source: "Origin",
    interactive: "Interactive session",
    auxiliarySource: "Auxiliary session",
  },
  "ja-JP": {
    options: "一覧の設定",
    agent: "Agent",
    allAgents: "すべての Agent",
    records: "記録の種類",
    current: "現在",
    archived: "アーカイブ",
    metadata: "メタデータのみ",
    all: "すべて",
    auxiliary: "補助セッションを表示",
    missing: "プロジェクト情報を取得できません。デスクトップを更新してください。",
    noResults: "該当するセッションはありません",
    project: "プロジェクト",
    path: "フルパス",
    updated: "更新日時",
    created: "作成日時",
    branch: "ブランチ",
    branchAtCreation: "作成時のブランチ",
    executionDirectory: "Codex の作業ディレクトリ",
    codexProjectId: "Codex プロジェクト ID",
    contextLoading: "Codex の情報を取得中…",
    contextUnavailable: "Codex の情報を取得できません",
    codexContextNote:
      "Codex のスレッド情報を表示しています。スマートフォンからの Codex ワークツリー作成や開始ブランチの指定には未対応です。ディレクトリのパスからワークツリーの種類は判別しません。",
    fork: "分岐元",
    spawned: "派生元",
    unknown: "不明",
    source: "種類",
    interactive: "対話セッション",
    auxiliarySource: "補助セッション",
  },
} satisfies Record<Locale, Record<string, string>>;
