import type { McpDiagnosticMessage } from "@agentkib/runtime-protocol";
import { mcpDiagnostic } from "./mcp-diagnostics";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { z } from "zod";
import { parseManifest, manifestPath } from "./manifest";
import { hash } from "./doctor-files";
import { maybeText } from "./files";
import { lexicalPathIdentity } from "./paths";
import { applyRequest } from "./changes";
import type { ChangeSet } from "./change-plan";
import type { BackendStore } from "./store";
import { resolveWorkspaceIdentity } from "./workspace-identity";
import { agentInstallations } from "./native-discovery-configured";
import {
  inspectMcpConnection,
  planMcpConnections,
  MCP_CONNECTION_AGENTS,
  type McpConnectionAgent,
  type McpConnectionInfo,
} from "./mcp-connection";

export type McpConnectionCheckStatus =
  | "missing"
  | "correct"
  | "repair"
  | "other-workspace"
  | "blocked"
  | "uninstalled";
export interface McpConnectionBatchRequest {
  workspaceId: string;
  targetAgents?: McpConnectionAgent[];
  all?: boolean;
  rebindAgents?: McpConnectionAgent[];
}
export interface McpConnectionCheckTarget {
  agent: McpConnectionAgent;
  status: McpConnectionCheckStatus;
  selected: boolean;
  installed: boolean;
  reason: string;
  reason_message?: McpDiagnosticMessage;
  target?: string;
  scope?: "project" | "agent-home";
  url?: string;
  disabled?: boolean;
}
export interface McpConnectionBatchCheck {
  workspace_id: string;
  targets: McpConnectionCheckTarget[];
}
export interface McpConnectionBatchPlan extends McpConnectionBatchCheck {
  token: string;
  changes: Array<{
    target: string;
    scope: "project" | "agent-home" | "application-data";
    before: string;
    after: string;
  }>;
  requires_home_approval: boolean;
}
export interface McpConnectionBatchResult {
  workspace_id: string;
  changeset_id: string;
  targets: Array<{
    agent: McpConnectionAgent;
    target?: string;
    status: "applied" | "unchanged" | "skipped" | "rolled-back" | "recovery-incomplete";
    reason: string;
    reason_message?: McpDiagnosticMessage;
  }>;
  success: boolean;
  backup_dir?: string;
  message?: string;
  diagnostics?: McpDiagnosticMessage[];
  recovery?: Array<{
    target: string;
    status: "restored" | "unconfirmed";
    backup?: string;
  }>;
}
const requestSchema = z
  .object({
    workspaceId: z.string().trim().min(1),
    targetAgents: z.array(z.enum(MCP_CONNECTION_AGENTS)).min(1).max(8).optional(),
    all: z.boolean().optional(),
    rebindAgents: z.array(z.enum(MCP_CONNECTION_AGENTS)).max(8).default([]),
  })
  .strict()
  .refine((request) => Boolean(request.all) !== Boolean(request.targetAgents), {
    message: "Select explicit Agents or all supported Agents",
  });
type Request = z.infer<typeof requestSchema>;
type Hub = { running: boolean; port: number };
type Inspection = ReturnType<typeof inspectMcpConnection>;
type Checked = {
  request: Request;
  response: McpConnectionBatchCheck;
  fingerprint: string;
  project: string;
  inspections: Map<McpConnectionAgent, Inspection>;
};
type Pending = {
  checked: Checked;
  plan: ChangeSet;
  expires: number;
  result?: McpConnectionBatchResult;
};

function publicConnection(info: McpConnectionInfo, existing: Inspection["existing"]): string {
  if (existing === undefined) return "";
  // Only expose the fields this operation owns. Unrelated native configuration,
  // headers, environment values and YAML comments never leave the backend.
  const source = existing as Record<string, unknown>,
    output: Record<string, unknown> = {};
  for (const key of ["type", "transport", "url", "serverUrl", "enabled", "disabled"])
    if (Object.hasOwn(source, key)) output[key] = source[key];
  return JSON.stringify({ agent: info.target_agent, agentkib: output }, null, 2);
}

function applyFailure(error: unknown): { text: string; diagnostic: McpDiagnosticMessage } {
  const code = (error as NodeJS.ErrnoException | null)?.code;
  if (typeof code === "string" && /^E[A-Z0-9_]{1,30}$/.test(code))
    return {
      text: `Configuration filesystem operation failed (${code})`,
      diagnostic: mcpDiagnostic("write_filesystem", { code }),
    };
  const message = error instanceof Error ? error.message : "";
  // These causes are generated by the writer, never by parsing private file data.
  for (const [prefix, explanation, key] of [
    [
      "File was modified externally:",
      "Configuration changed externally during application",
      "write_changed",
    ],
    [
      "Post-write validation failed:",
      "Configuration failed validation after writing",
      "write_validation",
    ],
    [
      "Refusing to write outside the project:",
      "Configuration path left the approved workspace",
      "write_outside",
    ],
    ["Agent Home", "The approved Agent Home target changed or is unavailable", "write_home"],
    ["Path contains", "Configuration contains an unsafe path", "write_unsafe"],
    ["ChangeSet overlaps", "Configuration overlaps a managed Skill deployment", "write_overlap"],
  ])
    if (message.startsWith(prefix!)) return { text: explanation!, diagnostic: mcpDiagnostic(key!) };
  return {
    text: "Configuration could not be safely written",
    diagnostic: mcpDiagnostic("write_failed"),
  };
}

/** Local desktop-only preparation and checked application of Hub connection files. */
export class McpConnectionBatch {
  readonly #pending = new Map<string, Pending>();

  constructor(
    readonly store: BackendStore,
    readonly dataDir: string,
    readonly environment: NodeJS.ProcessEnv,
    readonly hubStatus: () => Hub,
    readonly installations: () => Array<{ agent: string; installed: boolean }> = () =>
      agentInstallations(environment),
  ) {}

  #check(value: unknown): Checked {
    const request = requestSchema.parse(value),
      identity = resolveWorkspaceIdentity(this.store, request.workspaceId);
    if (identity.registeredId !== request.workspaceId)
      throw new Error("Select the registered workspace ID before connecting Agents");
    const agents = MCP_CONNECTION_AGENTS.filter((agent) =>
      request.all ? true : request.targetAgents!.includes(agent),
    );
    if (new Set(request.targetAgents).size !== (request.targetAgents?.length ?? 0))
      throw new Error("Duplicate Agent selection");
    if (request.rebindAgents.some((agent) => !agents.includes(agent)))
      throw new Error("Rebinding is limited to selected Agents");
    const installed = new Set(
        this.installations()
          .filter((item) => item.installed)
          .map((item) => item.agent),
      ),
      currentHub = this.hubStatus(),
      hub = { running: currentHub.running, port: currentHub.port },
      targets: McpConnectionCheckTarget[] = [],
      inspections = new Map<McpConnectionAgent, Inspection>(),
      snapshots: unknown[] = [];
    for (const agent of agents) {
      const target: McpConnectionCheckTarget = {
        agent,
        installed: installed.has(agent),
        selected: false,
        status: "uninstalled",
        reason: "Agent is not installed; its configuration will not be created",
        reason_message: mcpDiagnostic("connection_uninstalled"),
      };
      targets.push(target);
      if (!target.installed) continue;
      try {
        const inspection = inspectMcpConnection(
          { workspaceId: identity.registeredId, targetAgent: agent },
          this.store,
          hub,
          this.environment,
        );
        inspections.set(agent, inspection);
        const { info, before, existing, boundWorkspaceId } = inspection;
        Object.assign(target, { target: info.target, scope: info.scope, url: info.url });
        target.disabled =
          existing !== undefined && (existing.enabled === false || existing.disabled === true);
        snapshots.push({ agent, info, hash: before === null ? null : hash(before) });
        if (boundWorkspaceId === undefined) {
          target.status = "missing";
          target.selected = true;
          target.reason = "The AgentKib Hub connection is missing";
          target.reason_message = mcpDiagnostic("connection_missing");
        } else {
          const bound = resolveWorkspaceIdentity(this.store, boundWorkspaceId);
          snapshots.push({ agent, bound });
          const same =
            bound.registeredId === identity.registeredId &&
            lexicalPathIdentity(bound.project) === lexicalPathIdentity(identity.project);
          if (!same) {
            target.status = "other-workspace";
            target.selected = request.rebindAgents.includes(agent);
            target.reason_message = mcpDiagnostic(
              target.selected ? "connection_rebind" : "connection_other_workspace",
            );
            target.reason = target.selected
              ? "Explicitly rebind the existing connection to the selected workspace"
              : "The connection belongs to another registered workspace; rebinding is not selected";
          } else {
            target.status = inspection.needsRepair ? "repair" : "correct";
            target.selected = target.status === "repair";
            target.reason_message = mcpDiagnostic(
              target.status === "correct" ? "connection_correct" : "connection_repair",
            );
            target.reason =
              target.status === "correct"
                ? "Already connected to this workspace; no changes required"
                : "Repair the existing workspace connection and preserve its enabled state";
          }
        }
        // Run the exact merge validation for selected files without writing anything.
        if (target.selected)
          planMcpConnections(
            [{ workspaceId: identity.registeredId, targetAgent: agent }],
            this.store,
            hub,
            this.environment,
          );
      } catch {
        target.status = "blocked";
        target.reason_message = mcpDiagnostic("connection_blocked");
        target.selected = false;
        target.reason =
          "Configuration is unsafe, damaged, has an unknown agentkib entry, or its workspace identity is ambiguous; inspect it before retrying";
      }
    }
    const manifest = maybeText(manifestPath(identity.project), 8 * 1024 * 1024);
    return {
      request,
      project: identity.project,
      response: { workspace_id: identity.registeredId, targets },
      inspections,
      fingerprint: hash(
        JSON.stringify({
          request,
          identity,
          hub,
          targets,
          snapshots,
          manifest: manifest === null ? null : hash(manifest),
        }),
      ),
    };
  }

  check(value: unknown): McpConnectionBatchCheck {
    return this.#check(value).response;
  }

  plan(value: unknown): McpConnectionBatchPlan {
    const checked = this.#check(value),
      selected = checked.response.targets.filter((target) => target.selected),
      plan: ChangeSet = selected.length
        ? planMcpConnections(
            selected.map((target) => ({
              workspaceId: checked.response.workspace_id,
              targetAgent: target.agent,
            })),
            this.store,
            this.hubStatus(),
            this.environment,
          )
        : {
            id: randomUUID(),
            project_root: checked.project,
            created_at: new Date().toISOString(),
            changes: [],
            requires_home_approval: false,
          };
    if (checked.fingerprint !== this.#check(checked.request).fingerprint)
      throw new Error("MCP connection context changed while planning; preview again");
    const token = randomUUID();
    for (const [id, pending] of this.#pending)
      if (pending.expires < Date.now()) this.#pending.delete(id);
    if (this.#pending.size >= 32) this.#pending.delete(this.#pending.keys().next().value!);
    this.#pending.set(token, { checked, plan, expires: Date.now() + 10 * 60_000 });
    return {
      ...checked.response,
      token,
      requires_home_approval: plan.requires_home_approval,
      changes: plan.changes.map((change) => {
        if (change.target === manifestPath(checked.project)) {
          const summarize = (content: string) => {
            const manifest = parseManifest(content);
            return JSON.stringify(
              Object.fromEntries(
                selected.map(({ agent }) => [
                  agent,
                  manifest.adapters[agent]?.generated_hashes ?? {},
                ]),
              ),
              null,
              2,
            );
          };
          return { ...change, before: summarize(change.before), after: summarize(change.after) };
        }
        const inspection = [...checked.inspections.values()].find(
          (item) => item.info.target === change.target,
        )!;
        const after: Record<string, unknown> = {
          ...inspection.entry,
          ...(inspection.existing?.enabled !== undefined
            ? { enabled: inspection.existing.enabled }
            : {}),
          ...(inspection.existing?.disabled !== undefined
            ? { disabled: inspection.existing.disabled }
            : {}),
        };
        return {
          target: change.target,
          scope: change.scope,
          before: publicConnection(inspection.info, inspection.existing),
          after: publicConnection(inspection.info, after),
        };
      }),
    };
  }

  apply(value: unknown): McpConnectionBatchResult {
    const request = z
        .object({ token: z.string().uuid(), approveHome: z.boolean() })
        .strict()
        .parse(value),
      pending = this.#pending.get(request.token);
    if (!pending || pending.expires < Date.now())
      throw new Error("MCP connection preview expired; preview again");
    if (pending.result) return structuredClone(pending.result);
    if (pending.plan.requires_home_approval && !request.approveHome)
      throw new Error("Agent Home changes require separate confirmation");
    if (pending.checked.fingerprint !== this.#check(pending.checked.request).fingerprint) {
      this.#pending.delete(request.token);
      throw new Error("MCP connection context changed; preview again");
    }
    const result: McpConnectionBatchResult = {
      workspace_id: pending.checked.response.workspace_id,
      changeset_id: pending.plan.id,
      success: true,
      targets: pending.checked.response.targets.map((target) => ({
        agent: target.agent,
        target: target.target,
        status: target.status === "correct" ? "unchanged" : target.selected ? "applied" : "skipped",
        reason_message: target.selected
          ? mcpDiagnostic("connection_written")
          : target.reason_message,
        reason: target.selected
          ? "Hub connection written; reload the target Agent to use the updated configuration"
          : target.reason,
      })),
    };
    try {
      if (pending.plan.changes.length) {
        const report = applyRequest(
          { changeSet: pending.plan, approveHome: request.approveHome },
          this.store,
          this.dataDir,
          this.environment,
        );
        result.backup_dir = report.backup_dir;
      }
    } catch (error) {
      result.success = false;
      result.backup_dir = path.join(this.dataDir, "backups", pending.plan.id);
      result.recovery = [];
      let incomplete = false;
      for (const [index, change] of pending.plan.changes.entries()) {
        let restored = false;
        try {
          const current = maybeText(change.target, 8 * 1024 * 1024);
          restored = (current === null ? null : hash(current)) === change.original_hash;
        } catch {
          // An unreadable or externally replaced file cannot be claimed as recovered.
        }
        if (!restored) incomplete = true;
        result.recovery.push({
          target: change.target,
          status: restored ? "restored" : "unconfirmed",
          ...(change.original_hash === null
            ? {}
            : { backup: path.join(result.backup_dir, `${index}.bak`) }),
        });
        for (const target of result.targets)
          if (target.target === change.target && target.status === "applied") {
            target.status = restored ? "rolled-back" : "recovery-incomplete";
            target.reason_message = mcpDiagnostic(
              restored ? "connection_rolled_back" : "connection_recovery_incomplete",
            );
            target.reason = restored
              ? "The batch failed; this file matches its original contents"
              : "The batch failed and recovery could not be confirmed; inspect the file and backup";
          }
      }
      const failure = applyFailure(error);
      result.diagnostics = [
        failure.diagnostic,
        mcpDiagnostic(incomplete ? "recovery_incomplete" : "recovery_complete"),
      ];
      result.message = `${failure.text}. ${
        incomplete
          ? "Recovery is incomplete. Inspect the listed files and restricted backup directory."
          : "All planned files match their original contents. Preview again before retrying."
      }`;
    }
    pending.result = structuredClone(result);
    return result;
  }
}
