/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as settingsRouteRouteImport } from './routes/(settings)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainAgentsRouteImport } from './routes/(main)/agents'
import { Route as mainCatalogRouteImport } from './routes/(main)/catalog'
import { Route as mainInsightsRouteImport } from './routes/(main)/insights'
import { Route as mainQuotaRouteImport } from './routes/(main)/quota'
import { Route as mainSessionsRouteImport } from './routes/(main)/sessions'
import { Route as mainWorkspacesRouteImport } from './routes/(main)/workspaces'
import { Route as settingsSettingsRouteImport } from './routes/(settings)/settings'
import { Route as mainWorkspaceWorkspaceIdRouteRouteImport } from './routes/(main)/workspace/$workspaceId/route'
import { Route as mainWorkspaceWorkspaceIdIndexRouteImport } from './routes/(main)/workspace/$workspaceId/index'
import { Route as mainWorkspaceWorkspaceIdAssetsRouteImport } from './routes/(main)/workspace/$workspaceId/assets'
import { Route as mainWorkspaceWorkspaceIdChangesRouteImport } from './routes/(main)/workspace/$workspaceId/changes'
import { Route as mainWorkspaceWorkspaceIdContextRouteImport } from './routes/(main)/workspace/$workspaceId/context'
import { Route as mainWorkspaceWorkspaceIdDoctorRouteImport } from './routes/(main)/workspace/$workspaceId/doctor'
import { Route as mainWorkspaceWorkspaceIdGitRouteImport } from './routes/(main)/workspace/$workspaceId/git'
import { Route as mainWorkspaceWorkspaceIdSessionsRouteImport } from './routes/(main)/workspace/$workspaceId/sessions'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const settingsRouteRoute = settingsRouteRouteImport.update({
  id: '/(settings)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAgentsRoute = mainAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainCatalogRoute = mainCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainInsightsRoute = mainInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainQuotaRoute = mainQuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSessionsRoute = mainSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainWorkspacesRoute = mainWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => mainRouteRoute,
} as any)
const settingsSettingsRoute = settingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => settingsRouteRoute,
} as any)
const mainWorkspaceWorkspaceIdRouteRoute =
  mainWorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdIndexRoute =
  mainWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdAssetsRoute =
  mainWorkspaceWorkspaceIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdChangesRoute =
  mainWorkspaceWorkspaceIdChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdContextRoute =
  mainWorkspaceWorkspaceIdContextRouteImport.update({
    id: '/context',
    path: '/context',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdDoctorRoute =
  mainWorkspaceWorkspaceIdDoctorRouteImport.update({
    id: '/doctor',
    path: '/doctor',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdGitRoute =
  mainWorkspaceWorkspaceIdGitRouteImport.update({
    id: '/git',
    path: '/git',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)
const mainWorkspaceWorkspaceIdSessionsRoute =
  mainWorkspaceWorkspaceIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => mainWorkspaceWorkspaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/agents': typeof mainAgentsRoute
  '/catalog': typeof mainCatalogRoute
  '/insights': typeof mainInsightsRoute
  '/quota': typeof mainQuotaRoute
  '/sessions': typeof mainSessionsRoute
  '/workspaces': typeof mainWorkspacesRoute
  '/settings': typeof settingsSettingsRoute
  '/': typeof mainIndexRoute
  '/workspace/$workspaceId': typeof mainWorkspaceWorkspaceIdRouteRouteWithChildren
  '/workspace/$workspaceId/assets': typeof mainWorkspaceWorkspaceIdAssetsRoute
  '/workspace/$workspaceId/changes': typeof mainWorkspaceWorkspaceIdChangesRoute
  '/workspace/$workspaceId/context': typeof mainWorkspaceWorkspaceIdContextRoute
  '/workspace/$workspaceId/doctor': typeof mainWorkspaceWorkspaceIdDoctorRoute
  '/workspace/$workspaceId/git': typeof mainWorkspaceWorkspaceIdGitRoute
  '/workspace/$workspaceId/sessions': typeof mainWorkspaceWorkspaceIdSessionsRoute
  '/workspace/$workspaceId/': typeof mainWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/agents': typeof mainAgentsRoute
  '/catalog': typeof mainCatalogRoute
  '/insights': typeof mainInsightsRoute
  '/quota': typeof mainQuotaRoute
  '/sessions': typeof mainSessionsRoute
  '/workspaces': typeof mainWorkspacesRoute
  '/settings': typeof settingsSettingsRoute
  '/': typeof mainIndexRoute
  '/workspace/$workspaceId/assets': typeof mainWorkspaceWorkspaceIdAssetsRoute
  '/workspace/$workspaceId/changes': typeof mainWorkspaceWorkspaceIdChangesRoute
  '/workspace/$workspaceId/context': typeof mainWorkspaceWorkspaceIdContextRoute
  '/workspace/$workspaceId/doctor': typeof mainWorkspaceWorkspaceIdDoctorRoute
  '/workspace/$workspaceId/git': typeof mainWorkspaceWorkspaceIdGitRoute
  '/workspace/$workspaceId/sessions': typeof mainWorkspaceWorkspaceIdSessionsRoute
  '/workspace/$workspaceId': typeof mainWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(settings)': typeof settingsRouteRouteWithChildren
  '/(main)/agents': typeof mainAgentsRoute
  '/(main)/catalog': typeof mainCatalogRoute
  '/(main)/insights': typeof mainInsightsRoute
  '/(main)/quota': typeof mainQuotaRoute
  '/(main)/sessions': typeof mainSessionsRoute
  '/(main)/workspaces': typeof mainWorkspacesRoute
  '/(settings)/settings': typeof settingsSettingsRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/workspace/$workspaceId': typeof mainWorkspaceWorkspaceIdRouteRouteWithChildren
  '/(main)/workspace/$workspaceId/assets': typeof mainWorkspaceWorkspaceIdAssetsRoute
  '/(main)/workspace/$workspaceId/changes': typeof mainWorkspaceWorkspaceIdChangesRoute
  '/(main)/workspace/$workspaceId/context': typeof mainWorkspaceWorkspaceIdContextRoute
  '/(main)/workspace/$workspaceId/doctor': typeof mainWorkspaceWorkspaceIdDoctorRoute
  '/(main)/workspace/$workspaceId/git': typeof mainWorkspaceWorkspaceIdGitRoute
  '/(main)/workspace/$workspaceId/sessions': typeof mainWorkspaceWorkspaceIdSessionsRoute
  '/(main)/workspace/$workspaceId/': typeof mainWorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agents'
    | '/catalog'
    | '/insights'
    | '/quota'
    | '/sessions'
    | '/workspaces'
    | '/settings'
    | '/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/assets'
    | '/workspace/$workspaceId/changes'
    | '/workspace/$workspaceId/context'
    | '/workspace/$workspaceId/doctor'
    | '/workspace/$workspaceId/git'
    | '/workspace/$workspaceId/sessions'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/catalog'
    | '/insights'
    | '/quota'
    | '/sessions'
    | '/workspaces'
    | '/settings'
    | '/'
    | '/workspace/$workspaceId/assets'
    | '/workspace/$workspaceId/changes'
    | '/workspace/$workspaceId/context'
    | '/workspace/$workspaceId/doctor'
    | '/workspace/$workspaceId/git'
    | '/workspace/$workspaceId/sessions'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/(main)'
    | '/(settings)'
    | '/(main)/agents'
    | '/(main)/catalog'
    | '/(main)/insights'
    | '/(main)/quota'
    | '/(main)/sessions'
    | '/(main)/workspaces'
    | '/(settings)/settings'
    | '/(main)/'
    | '/(main)/workspace/$workspaceId'
    | '/(main)/workspace/$workspaceId/assets'
    | '/(main)/workspace/$workspaceId/changes'
    | '/(main)/workspace/$workspaceId/context'
    | '/(main)/workspace/$workspaceId/doctor'
    | '/(main)/workspace/$workspaceId/git'
    | '/(main)/workspace/$workspaceId/sessions'
    | '/(main)/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  settingsRouteRoute: typeof settingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(settings)': {
      id: '/(settings)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof settingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/agents': {
      id: '/(main)/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof mainAgentsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/catalog': {
      id: '/(main)/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof mainCatalogRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/insights': {
      id: '/(main)/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof mainInsightsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/quota': {
      id: '/(main)/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof mainQuotaRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/sessions': {
      id: '/(main)/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof mainSessionsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/workspaces': {
      id: '/(main)/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof mainWorkspacesRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(settings)/settings': {
      id: '/(settings)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof settingsSettingsRouteImport
      parentRoute: typeof settingsRouteRoute
    }
    '/(main)/workspace/$workspaceId': {
      id: '/(main)/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/workspace/$workspaceId/': {
      id: '/(main)/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
    '/(main)/workspace/$workspaceId/assets': {
      id: '/(main)/workspace/$workspaceId/assets'
      path: '/assets'
      fullPath: '/workspace/$workspaceId/assets'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdAssetsRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
    '/(main)/workspace/$workspaceId/changes': {
      id: '/(main)/workspace/$workspaceId/changes'
      path: '/changes'
      fullPath: '/workspace/$workspaceId/changes'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdChangesRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
    '/(main)/workspace/$workspaceId/context': {
      id: '/(main)/workspace/$workspaceId/context'
      path: '/context'
      fullPath: '/workspace/$workspaceId/context'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdContextRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
    '/(main)/workspace/$workspaceId/doctor': {
      id: '/(main)/workspace/$workspaceId/doctor'
      path: '/doctor'
      fullPath: '/workspace/$workspaceId/doctor'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdDoctorRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
    '/(main)/workspace/$workspaceId/git': {
      id: '/(main)/workspace/$workspaceId/git'
      path: '/git'
      fullPath: '/workspace/$workspaceId/git'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdGitRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
    '/(main)/workspace/$workspaceId/sessions': {
      id: '/(main)/workspace/$workspaceId/sessions'
      path: '/sessions'
      fullPath: '/workspace/$workspaceId/sessions'
      preLoaderRoute: typeof mainWorkspaceWorkspaceIdSessionsRouteImport
      parentRoute: typeof mainWorkspaceWorkspaceIdRouteRoute
    }
  }
}

interface mainWorkspaceWorkspaceIdRouteRouteChildren {
  mainWorkspaceWorkspaceIdAssetsRoute: typeof mainWorkspaceWorkspaceIdAssetsRoute
  mainWorkspaceWorkspaceIdChangesRoute: typeof mainWorkspaceWorkspaceIdChangesRoute
  mainWorkspaceWorkspaceIdContextRoute: typeof mainWorkspaceWorkspaceIdContextRoute
  mainWorkspaceWorkspaceIdDoctorRoute: typeof mainWorkspaceWorkspaceIdDoctorRoute
  mainWorkspaceWorkspaceIdGitRoute: typeof mainWorkspaceWorkspaceIdGitRoute
  mainWorkspaceWorkspaceIdSessionsRoute: typeof mainWorkspaceWorkspaceIdSessionsRoute
  mainWorkspaceWorkspaceIdIndexRoute: typeof mainWorkspaceWorkspaceIdIndexRoute
}

const mainWorkspaceWorkspaceIdRouteRouteChildren: mainWorkspaceWorkspaceIdRouteRouteChildren =
  {
    mainWorkspaceWorkspaceIdAssetsRoute: mainWorkspaceWorkspaceIdAssetsRoute,
    mainWorkspaceWorkspaceIdChangesRoute: mainWorkspaceWorkspaceIdChangesRoute,
    mainWorkspaceWorkspaceIdContextRoute: mainWorkspaceWorkspaceIdContextRoute,
    mainWorkspaceWorkspaceIdDoctorRoute: mainWorkspaceWorkspaceIdDoctorRoute,
    mainWorkspaceWorkspaceIdGitRoute: mainWorkspaceWorkspaceIdGitRoute,
    mainWorkspaceWorkspaceIdSessionsRoute:
      mainWorkspaceWorkspaceIdSessionsRoute,
    mainWorkspaceWorkspaceIdIndexRoute: mainWorkspaceWorkspaceIdIndexRoute,
  }

const mainWorkspaceWorkspaceIdRouteRouteWithChildren =
  mainWorkspaceWorkspaceIdRouteRoute._addFileChildren(
    mainWorkspaceWorkspaceIdRouteRouteChildren,
  )

interface mainRouteRouteChildren {
  mainAgentsRoute: typeof mainAgentsRoute
  mainCatalogRoute: typeof mainCatalogRoute
  mainInsightsRoute: typeof mainInsightsRoute
  mainQuotaRoute: typeof mainQuotaRoute
  mainSessionsRoute: typeof mainSessionsRoute
  mainWorkspacesRoute: typeof mainWorkspacesRoute
  mainIndexRoute: typeof mainIndexRoute
  mainWorkspaceWorkspaceIdRouteRoute: typeof mainWorkspaceWorkspaceIdRouteRouteWithChildren
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAgentsRoute: mainAgentsRoute,
  mainCatalogRoute: mainCatalogRoute,
  mainInsightsRoute: mainInsightsRoute,
  mainQuotaRoute: mainQuotaRoute,
  mainSessionsRoute: mainSessionsRoute,
  mainWorkspacesRoute: mainWorkspacesRoute,
  mainIndexRoute: mainIndexRoute,
  mainWorkspaceWorkspaceIdRouteRoute:
    mainWorkspaceWorkspaceIdRouteRouteWithChildren,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface settingsRouteRouteChildren {
  settingsSettingsRoute: typeof settingsSettingsRoute
}

const settingsRouteRouteChildren: settingsRouteRouteChildren = {
  settingsSettingsRoute: settingsSettingsRoute,
}

const settingsRouteRouteWithChildren = settingsRouteRoute._addFileChildren(
  settingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  settingsRouteRoute: settingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
