import { dictionaries, type Locale } from "../../i18n";
import { unavailableReasonText } from "../../live-status";
const zh = {
  handoff: "我已处理待审批事项和后台命令，并关闭原执行客户端；以原任务 ID 恢复，不自动分支。",
  composerHint: "空闲时发送；运行中可停止，获授权后可追加或加入原生队列。队列消息将自动执行。",
  queueTooLarge: "原生队列超过 100 条，请先在原客户端处理；此处暂不允许编辑或排序。",
  queueAttachments: "含附件的待发消息暂不支持编辑正文，可删除后重新添加。",
  keep: "保持当前设置",
  pendingInfo: "汇总本页已查看会话的待处理事项及本浏览器尚未确认的请求。",
  title: "Codex 控制",
  capabilities: "主机能力",
  unavailable: "主机未提供或尚未验证此能力",
  permission: "需要桌面单独授权",
  resume: "继续 / 恢复",
  inspect: "核对原生状态",
  steer: "追加到当前轮次",
  queue: "原生待发送队列",
  queueAdd: "加入队列（将自动执行）",
  queueUpdate: "修改",
  queueDelete: "移除",
  queueUp: "上移",
  queueStart: "开始队列",
  queueEmpty: "队列为空",
  rename: "重命名",
  archive: "归档",
  unarchive: "取消归档",
  fork: "分支会话",
  name: "会话名称",
  settings: "下一轮设置",
  model: "模型",
  effort: "思考强度",
  mode: "协作模式",
  default: "主机默认",
  plan: "计划",
  normal: "执行",
  apply: "应用到下一轮",
  attachment: "添加附件",
  attachmentNote: "选择文件或粘贴图片；上传只暂存，发送后才加入会话。",
  previewAttachment: "预览附件",
  uploading: "上传中",
  uploadFailed: "上传失败，请重新选择文件",
  remove: "移除附件",
  limit: "最多选择 10 个附件",
  pending: "待处理中心",
  pendingEmpty: "没有待处理事项",
  refresh: "刷新",
  advanced: "更多操作",
  native: "原生审批选项",
  once: "仅本次",
  session: "本会话",
  persistent: "持久规则",
  unavailableQueue: "无法读取队列",
  accepted: "请求已接受，请以原生状态为准",
  context: "原生上下文",
  secret: "敏感回答不会保存为草稿",
  unknown: "上次操作结果未确认，正在核对回执；不会自动重发",
  error: "读取失败，请刷新",
  confirmation: "确认操作",
  close: "关闭",
  text: "消息内容",
  conversationSettings: "对话设置",
  restoreDefaults: "恢复主机默认",
  serviceTier: "服务档位",
  executionPolicy: "执行策略",
  contextUsage: "上下文用量",
  contextUnknown: "主机尚未提供上下文窗口用量",
  settingUnavailable: "此会话暂不支持修改该设置",
  settingsWhileRunning: "当前轮次结束后才能修改设置",
  settingsSaved: "设置已由主机确认",
  goals: "持续目标",
  goalObjective: "目标内容",
  goalBudget: "Token 预算（可选）",
  goalCreate: "开始目标",
  goalUpdate: "更新目标",
  goalPause: "暂停",
  goalResume: "恢复并继续执行",
  goalClear: "清除目标",
  goalUnavailable: "主机尚未提供目标管理",
  goalStatus: "状态",
  goalUsage: "消耗",
  goalElapsed: "运行时间",
  addContext: "添加上下文",
  uploadFromPhone: "上传手机文件",
  computerFiles: "电脑文件与文件夹",
  skillsPlugins: "技能、插件与应用",
  resourceSearch: "搜索可用资源",
  resourceEmpty: "没有可用资源",
  resourceUnavailable: "主机尚未提供受控上下文引用",
  resourceRemoved: "资源已失效，请重新选择",
  fullAccessRequired: "请使用新的完整授权码连接后操作",
  directoryReference: "文件夹仅作为引用，不会递归上传",
  defaultOption: "默认",
};
type Copy = { [K in keyof typeof zh]: string };
export const codexCopy: Record<Locale, Copy> = {
  "zh-CN": zh,
  "zh-TW": {
    previewAttachment: "預覽附件",
    composerHint: "閒置時傳送；執行中可停止，獲授權後可追加或加入原生佇列。佇列訊息將自動執行。",
    queueTooLarge: "原生佇列超過 100 條，請先在原客戶端處理；此處暫不允許編輯或排序。",
    queueAttachments: "含附件的待傳送訊息暫不支援編輯內文，可刪除後重新新增。",
    keep: "保持目前設定",
    pendingInfo: "彙整此頁已查看對話的待處理事項及此瀏覽器尚未確認的請求。",
    handoff: "我已處理待審批事項和背景命令，並關閉原執行客戶端；以原任務 ID 恢復，不自動分支。",
    title: "Codex 控制",
    capabilities: "主機能力",
    unavailable: "主機未提供或尚未驗證此能力",
    permission: "需要桌面單獨授權",
    resume: "繼續 / 恢復",
    inspect: "核對原生狀態",
    steer: "追加到目前輪次",
    queue: "原生待傳送佇列",
    queueAdd: "加入佇列（將自動執行）",
    queueUpdate: "修改",
    queueDelete: "移除",
    queueUp: "上移",
    queueStart: "開始佇列",
    queueEmpty: "佇列為空",
    rename: "重新命名",
    archive: "封存",
    unarchive: "取消封存",
    fork: "分支對話",
    name: "對話名稱",
    settings: "下一輪設定",
    model: "模型",
    effort: "思考強度",
    mode: "協作模式",
    default: "主機預設",
    plan: "計畫",
    normal: "執行",
    apply: "套用至下一輪",
    attachment: "新增附件",
    attachmentNote: "選取檔案或貼上圖片；上傳僅暫存，傳送後才加入對話。",
    uploading: "上傳中",
    uploadFailed: "上傳失敗，請重新選取檔案",
    remove: "移除附件",
    limit: "最多選取 10 個附件",
    pending: "待處理中心",
    pendingEmpty: "沒有待處理事項",
    refresh: "重新整理",
    advanced: "更多操作",
    native: "原生審批選項",
    once: "僅本次",
    session: "本對話",
    persistent: "持久規則",
    unavailableQueue: "無法讀取佇列",
    accepted: "請求已接受，請以原生狀態為準",
    context: "原生上下文",
    secret: "敏感回答不會儲存為草稿",
    unknown: "上次操作結果未確認，正在核對回執；不會自動重傳",
    error: "讀取失敗，請重新整理",
    confirmation: "確認操作",
    close: "關閉",
    text: "訊息內容",
    conversationSettings: "對話設定",
    restoreDefaults: "恢復主機預設",
    serviceTier: "服務等級",
    executionPolicy: "執行策略",
    contextUsage: "上下文用量",
    contextUnknown: "主機尚未提供上下文視窗用量",
    settingUnavailable: "此對話暫不支援修改此設定",
    settingsWhileRunning: "目前輪次結束後才能修改設定",
    settingsSaved: "設定已由主機確認",
    goals: "持續目標",
    goalObjective: "目標內容",
    goalBudget: "Token 預算（選填）",
    goalCreate: "開始目標",
    goalUpdate: "更新目標",
    goalPause: "暫停",
    goalResume: "恢復並繼續執行",
    goalClear: "清除目標",
    goalUnavailable: "主機尚未提供目標管理",
    goalStatus: "狀態",
    goalUsage: "用量",
    goalElapsed: "執行時間",
    addContext: "新增上下文",
    uploadFromPhone: "上傳手機檔案",
    computerFiles: "電腦檔案與資料夾",
    skillsPlugins: "技能、外掛與應用程式",
    resourceSearch: "搜尋可用資源",
    resourceEmpty: "沒有可用資源",
    resourceUnavailable: "主機尚未提供受控上下文引用",
    resourceRemoved: "資源已失效，請重新選取",
    fullAccessRequired: "請使用新的完整授權碼連線後操作",
    directoryReference: "資料夾僅作為引用，不會遞迴上傳",
    defaultOption: "預設",
  },
  "en-US": {
    previewAttachment: "Preview attachment",
    composerHint:
      "Send when idle. While running, stop or—with permission—steer or queue messages. Native queued messages execute automatically.",
    queueTooLarge:
      "The native queue exceeds 100 items. Manage it in the original client first; editing and reordering are disabled here.",
    queueAttachments:
      "Queued messages with attachments cannot be edited yet. Remove and add them again instead.",
    keep: "Keep current settings",
    pendingInfo:
      "Pending actions from sessions viewed on this page and unconfirmed requests from this browser.",
    handoff:
      "I have handled pending requests and background commands and closed the original execution client. Resume the same task ID without an automatic fork.",
    title: "Codex controls",
    capabilities: "Host capabilities",
    unavailable: "The host does not provide or has not verified this capability",
    permission: "Separate desktop permission required",
    resume: "Continue / resume",
    inspect: "Inspect native state",
    steer: "Add to current turn",
    queue: "Native submission queue",
    queueAdd: "Queue for automatic execution",
    queueUpdate: "Edit",
    queueDelete: "Remove",
    queueUp: "Move up",
    queueStart: "Start queue",
    queueEmpty: "Queue is empty",
    rename: "Rename",
    archive: "Archive",
    unarchive: "Unarchive",
    fork: "Fork session",
    name: "Session name",
    settings: "Next-turn settings",
    model: "Model",
    effort: "Reasoning effort",
    mode: "Collaboration mode",
    default: "Host default",
    plan: "Plan",
    normal: "Execute",
    apply: "Apply to next turn",
    attachment: "Add attachments",
    attachmentNote:
      "Choose files or paste images. Uploads are staged and only join the conversation when sent.",
    uploading: "Uploading",
    uploadFailed: "Upload failed. Select the file again.",
    remove: "Remove attachment",
    limit: "Select up to 10 attachments",
    pending: "Pending actions",
    pendingEmpty: "No pending actions",
    refresh: "Refresh",
    advanced: "More actions",
    native: "Native approval options",
    once: "This time",
    session: "This session",
    persistent: "Persistent rule",
    unavailableQueue: "Cannot read the queue",
    accepted: "Request accepted; native state is authoritative",
    context: "Native context",
    secret: "Sensitive answers are never saved as drafts",
    unknown: "The last outcome is unknown. Checking its receipt without replaying it.",
    error: "Could not load. Refresh to retry.",
    confirmation: "Confirm action",
    close: "Close",
    text: "Message text",
    conversationSettings: "Conversation settings",
    restoreDefaults: "Restore host defaults",
    serviceTier: "Service tier",
    executionPolicy: "Execution policy",
    contextUsage: "Context usage",
    contextUnknown: "The host has not reported context-window usage",
    settingUnavailable: "This session cannot change this setting",
    settingsWhileRunning: "Settings can be changed after the current turn finishes",
    settingsSaved: "The host confirmed these settings",
    goals: "Persistent goal",
    goalObjective: "Objective",
    goalBudget: "Token budget (optional)",
    goalCreate: "Start goal",
    goalUpdate: "Update goal",
    goalPause: "Pause",
    goalResume: "Resume and continue",
    goalClear: "Clear goal",
    goalUnavailable: "The host does not provide goal management",
    goalStatus: "Status",
    goalUsage: "Usage",
    goalElapsed: "Elapsed time",
    addContext: "Add context",
    uploadFromPhone: "Upload phone files",
    computerFiles: "Computer files and folders",
    skillsPlugins: "Skills, plugins and apps",
    resourceSearch: "Search available resources",
    resourceEmpty: "No resources available",
    resourceUnavailable: "The host does not provide controlled context references",
    resourceRemoved: "This resource is no longer valid. Select it again.",
    fullAccessRequired: "Reconnect with a new full-access code to use this control",
    directoryReference: "Folders are referenced without recursively uploading their contents",
    defaultOption: "Default",
  },
  "ja-JP": {
    previewAttachment: "添付ファイルをプレビュー",
    composerHint:
      "待機中は送信できます。実行中は停止、許可があれば追加入力やキュー登録ができます。キューは自動実行されます。",
    queueTooLarge:
      "ネイティブキューが 100 件を超えています。元のクライアントで整理してください。ここでの編集と並べ替えは無効です。",
    queueAttachments:
      "添付付きの送信待ちメッセージは編集できません。削除して追加し直してください。",
    keep: "現在の設定を保持",
    pendingInfo:
      "このページで閲覧した会話の対応待ち項目と、このブラウザーの未確認リクエストを表示します。",
    handoff:
      "保留中のリクエストとバックグラウンドコマンドを確認し、元の実行クライアントを閉じました。自動分岐せず元のタスク ID で再開します。",
    title: "Codex 操作",
    capabilities: "ホストの機能",
    unavailable: "ホストで未提供または未検証の機能です",
    permission: "デスクトップで個別の許可が必要です",
    resume: "続行 / 再開",
    inspect: "ネイティブ状態を確認",
    steer: "現在のターンに追加",
    queue: "ネイティブ送信キュー",
    queueAdd: "キューに追加（自動実行）",
    queueUpdate: "編集",
    queueDelete: "削除",
    queueUp: "上へ移動",
    queueStart: "キューを開始",
    queueEmpty: "キューは空です",
    rename: "名前を変更",
    archive: "アーカイブ",
    unarchive: "アーカイブ解除",
    fork: "会話を分岐",
    name: "会話名",
    settings: "次のターンの設定",
    model: "モデル",
    effort: "推論の強度",
    mode: "協調モード",
    default: "ホストの既定値",
    plan: "計画",
    normal: "実行",
    apply: "次のターンに適用",
    attachment: "添付ファイルを追加",
    attachmentNote:
      "ファイルを選択するか画像を貼り付けます。アップロードは一時保存で、送信後に会話に追加されます。",
    uploading: "アップロード中",
    uploadFailed: "アップロードに失敗しました。ファイルを再選択してください。",
    remove: "添付を削除",
    limit: "添付は 10 件までです",
    pending: "対応待ち",
    pendingEmpty: "対応待ちはありません",
    refresh: "更新",
    advanced: "その他の操作",
    native: "ネイティブ承認の選択肢",
    once: "今回のみ",
    session: "この会話",
    persistent: "永続ルール",
    unavailableQueue: "キューを読み込めません",
    accepted: "リクエストを受け付けました。ネイティブ状態で確認してください",
    context: "ネイティブのコンテキスト",
    secret: "機密の回答は下書きとして保存されません",
    unknown: "前回の結果を確認中です。リクエストを再送しません",
    error: "読み込みに失敗しました。更新してください",
    confirmation: "操作を確認",
    close: "閉じる",
    text: "メッセージ内容",
    conversationSettings: "会話の設定",
    restoreDefaults: "ホストの既定値に戻す",
    serviceTier: "サービス階層",
    executionPolicy: "実行ポリシー",
    contextUsage: "コンテキスト使用量",
    contextUnknown: "ホストからコンテキストウィンドウの使用量が提供されていません",
    settingUnavailable: "このセッションではこの設定を変更できません",
    settingsWhileRunning: "現在のターンが終了してから設定を変更できます",
    settingsSaved: "ホストが設定を確認しました",
    goals: "継続目標",
    goalObjective: "目標",
    goalBudget: "Token 予算（任意）",
    goalCreate: "目標を開始",
    goalUpdate: "目標を更新",
    goalPause: "一時停止",
    goalResume: "再開して続行",
    goalClear: "目標をクリア",
    goalUnavailable: "ホストは目標管理を提供していません",
    goalStatus: "状態",
    goalUsage: "使用量",
    goalElapsed: "経過時間",
    addContext: "コンテキストを追加",
    uploadFromPhone: "スマートフォンのファイルをアップロード",
    computerFiles: "コンピューターのファイルとフォルダー",
    skillsPlugins: "スキル、プラグイン、アプリ",
    resourceSearch: "利用可能なリソースを検索",
    resourceEmpty: "利用可能なリソースはありません",
    resourceUnavailable: "ホストは制御されたコンテキスト参照を提供していません",
    resourceRemoved: "リソースが無効になりました。選択し直してください。",
    fullAccessRequired: "新しいフルアクセスコードで再接続してください",
    directoryReference: "フォルダーは再帰アップロードせず参照として追加されます",
    defaultOption: "デフォルト",
  },
};

const reasons: Record<Locale, Record<string, string>> = {
  "zh-CN": {
    "settings-not-applied": "设置尚未由 Codex 原生确认，请先发送一轮应用设置，再开始或恢复目标。",
    "collaboration-modes-unavailable": "主机尚未提供已验证的原生协作模式目录。",
    "session-busy": "此操作需要会话空闲，请等待当前轮次结束。",
    "session-requires-running-turn": "此操作仅在轮次运行中可用。",
    "no-active-turn": "当前没有可停止的轮次。",
    "session-already-managed": "AgentKib 已持有此会话，无需再次恢复。",
    "session-not-archived": "此会话尚未归档，无需取消归档。",
    "session-archived": "此会话已归档，请先取消归档。",
    "session-released": "此会话已释放，请先恢复执行。",
    "recovery-required": "执行连接需要恢复，请先核对原生状态。",
    "native-session-unconfirmed": "尚未确认原生会话标识，请先核对原生状态。",
    "follower-operation-unverified": "当前原生客户端尚未验证此操作，请在原客户端完成。",
    "control-disabled": "桌面尚未开启执行控制。",
    "session-state-unavailable": "暂时无法读取会话状态，请核对原客户端后刷新。",
    "unsupported-codex-cli-version": "当前 Codex 版本未经兼容验证，此能力保持只读。",
    "native-operation-not-integrated": "此原生操作尚未接入远控。",
    "control-outcome-unconfirmed": "上次执行结果尚未确认，请先核对原生状态与请求回执。",
    permission_denied: "此浏览器尚未获得对应权限，请在桌面授权。",
  },
  "zh-TW": {
    "settings-not-applied": "設定尚未由 Codex 原生確認，請先傳送一回合套用設定，再開始或恢復目標。",
    "collaboration-modes-unavailable": "主機尚未提供已驗證的原生協作模式目錄。",
    "session-busy": "此操作需要對話閒置，請等待目前輪次結束。",
    "session-requires-running-turn": "此操作僅在輪次執行中可用。",
    "no-active-turn": "目前沒有可停止的輪次。",
    "session-already-managed": "AgentKib 已持有此對話，無需再次恢復。",
    "session-not-archived": "此對話尚未封存，無需取消封存。",
    "session-archived": "此對話已封存，請先取消封存。",
    "session-released": "此對話已釋放，請先恢復執行。",
    "recovery-required": "執行連線需要恢復，請先核對原生狀態。",
    "native-session-unconfirmed": "尚未確認原生對話識別碼，請先核對原生狀態。",
    "follower-operation-unverified": "目前原生客戶端尚未驗證此操作，請在原客戶端完成。",
    "control-disabled": "桌面尚未啟用執行控制。",
    "session-state-unavailable": "暫時無法讀取對話狀態，請核對原客戶端後重新整理。",
    "unsupported-codex-cli-version": "目前 Codex 版本未經相容驗證，此能力保持唯讀。",
    "native-operation-not-integrated": "此原生操作尚未接入遠端控制。",
    "control-outcome-unconfirmed": "上次執行結果尚未確認，請先核對原生狀態與請求回執。",
    permission_denied: "此瀏覽器尚未取得對應權限，請在桌面授權。",
  },
  "en-US": {
    "settings-not-applied":
      "Codex has not confirmed these settings. Send a turn to apply them before starting or resuming the goal.",
    "collaboration-modes-unavailable":
      "The host has not provided a verified native collaboration mode list.",
    "session-busy": "This operation requires an idle session. Wait for the current turn to finish.",
    "session-requires-running-turn": "This operation is only available while a turn is running.",
    "no-active-turn": "There is no active turn to stop.",
    "session-already-managed":
      "AgentKib already holds this session. Resuming it again is unnecessary.",
    "session-not-archived": "This session is not archived, so there is nothing to unarchive.",
    "session-archived": "This session is archived. Unarchive it first.",
    "session-released": "This session has been released. Resume execution first.",
    "recovery-required": "The execution connection needs recovery. Check native state first.",
    "native-session-unconfirmed":
      "The native session identity is not confirmed. Check native state first.",
    "follower-operation-unverified":
      "This operation has not been verified with the original client. Use that client instead.",
    "control-disabled": "Execution control is not enabled on desktop.",
    "session-state-unavailable":
      "Session state is unavailable. Check the original client and refresh.",
    "unsupported-codex-cli-version":
      "This Codex version has not passed compatibility verification. This capability remains read-only.",
    "native-operation-not-integrated":
      "This native operation is not integrated into remote access yet.",
    "control-outcome-unconfirmed":
      "The previous outcome is unknown. Check native state and the saved receipt first.",
    permission_denied: "This browser needs the corresponding desktop permission.",
  },
  "ja-JP": {
    "settings-not-applied":
      "設定は Codex で未確認です。ターンを送信して反映した後、目標を開始または再開してください。",
    "collaboration-modes-unavailable":
      "ホストは検証済みのネイティブ協調モード一覧を提供していません。",
    "session-busy": "この操作は待機中に利用できます。現在のターンの終了をお待ちください。",
    "session-requires-running-turn": "この操作はターンの実行中のみ利用できます。",
    "no-active-turn": "停止できるターンはありません。",
    "session-already-managed":
      "AgentKib はすでにこの会話を管理しています。再開する必要はありません。",
    "session-not-archived": "この会話はアーカイブされていないため、解除する必要はありません。",
    "session-archived": "この会話はアーカイブされています。先にアーカイブを解除してください。",
    "session-released": "この会話の実行は引き渡されました。先に実行を再開してください。",
    "recovery-required": "実行接続の復旧が必要です。先にネイティブ状態を確認してください。",
    "native-session-unconfirmed":
      "ネイティブ会話の ID が未確認です。先にネイティブ状態を確認してください。",
    "follower-operation-unverified":
      "元のクライアントでこの操作は未検証です。元のクライアントで操作してください。",
    "control-disabled": "デスクトップで実行操作が有効になっていません。",
    "session-state-unavailable":
      "会話の状態を取得できません。元のクライアントを確認して更新してください。",
    "unsupported-codex-cli-version":
      "この Codex バージョンは互換性が未検証のため、この機能は読み取り専用です。",
    "native-operation-not-integrated": "このネイティブ操作はリモートアクセスに未対応です。",
    "control-outcome-unconfirmed":
      "前回の結果が未確認です。ネイティブ状態と保存済みリクエストの応答を確認してください。",
    permission_denied: "このブラウザーにはデスクトップで対応する権限を付与する必要があります。",
  },
};
export function codexReason(locale: Locale, reason?: string): { text: string; technical?: string } {
  if (reason === "unverified-installation" || reason === "open-in-original-client") {
    return { text: unavailableReasonText(reason, dictionaries[locale]) };
  }
  const text = reason ? reasons[locale][reason] : undefined;
  return text
    ? { text }
    : { text: codexCopy[locale].unavailable, ...(reason ? { technical: reason } : {}) };
}
