import type { Locale } from "@/i18n";

const copy = {
  "zh-CN": {
    resourceNeedsMessage: "引用文件或技能后，请输入消息或添加手机附件再发送。",
    details: "诊断详情",
    enterDirectory: "进入文件夹",
    parentDirectory: "返回上级",
    contextRoot: "工作区根目录",
    contextLoading: "正在加载资源…",
    contextRetry: "重试",
    tryResume: "尝试恢复",
    modeUnknown: "原生模式待确认",
    nativeChanged: "Codex 原生状态已变化，草稿已保留。重新载入后再提交。",
    reloadDraft: "重新载入",
    nextTurn: "下一轮",
    settingsPending: "已保存下一轮选择；发送后以 Codex 原生回读确认生效。",
    settingsUnknown: "设置生效状态待核对",
    done: "完成",
    selected: "已选",
    help: "发送说明",
    queue: "队列中的消息将在当前轮次结束后自动执行。",
    pending: "请求结果待核对，请勿重复发送。",
    offline: "连接已断开，恢复后才能发送。",
    connecting: "正在核对会话状态，请稍候。",
    readOnly: "当前会话仅可查看，发送能力尚不可用。",
    permission: "当前浏览器未获发送授权。",
    waiting: "请先处理待审批或回答的请求。",
  },
  "zh-TW": {
    resourceNeedsMessage: "引用檔案或技能後，請輸入訊息或新增手機附件再傳送。",
    details: "診斷詳情",
    enterDirectory: "進入資料夾",
    parentDirectory: "返回上層",
    contextRoot: "工作區根目錄",
    contextLoading: "正在載入資源…",
    contextRetry: "重試",
    tryResume: "嘗試恢復",
    modeUnknown: "原生模式待確認",
    nativeChanged: "Codex 原生狀態已變更，草稿已保留。重新載入後再提交。",
    reloadDraft: "重新載入",
    nextTurn: "下一回合",
    settingsPending: "已儲存下一回合選擇；傳送後以 Codex 原生回讀確認生效。",
    settingsUnknown: "設定生效狀態待核對",
    done: "完成",
    selected: "已選",
    help: "傳送說明",
    queue: "佇列中的訊息會在目前回合結束後自動執行。",
    pending: "請求結果待核對，請勿重複傳送。",
    offline: "連線已中斷，恢復後才能傳送。",
    connecting: "正在核對對話狀態，請稍候。",
    readOnly: "目前對話僅可檢視，傳送能力尚不可用。",
    permission: "目前瀏覽器未獲傳送授權。",
    waiting: "請先處理待核准或回答的請求。",
  },
  "en-US": {
    resourceNeedsMessage: "Add a message or upload an attachment to send file or skill references.",
    details: "Diagnostic details",
    enterDirectory: "Open folder",
    parentDirectory: "Parent folder",
    contextRoot: "Workspace root",
    contextLoading: "Loading resources…",
    contextRetry: "Retry",
    tryResume: "Try resuming",
    modeUnknown: "Native mode unconfirmed",
    nativeChanged: "Codex state changed. Your draft is preserved. Reload before submitting.",
    reloadDraft: "Reload",
    nextTurn: "Next turn",
    settingsPending: "Selection saved for the next turn. Codex must confirm it after sending.",
    settingsUnknown: "Setting status unconfirmed",
    done: "Done",
    selected: "Selected",
    help: "Sending help",
    queue: "Queued messages run automatically after the current turn.",
    pending: "The request outcome needs reconciliation. Do not send it again.",
    offline: "Disconnected. Reconnect before sending.",
    connecting: "Checking the conversation state…",
    readOnly: "This conversation is view-only; sending is unavailable.",
    permission: "This browser does not have permission to send.",
    waiting: "Resolve the pending approval or question first.",
  },
  "ja-JP": {
    resourceNeedsMessage:
      "ファイルやスキルの参照を送るには、メッセージを入力するか添付ファイルを追加してください。",
    details: "診断の詳細",
    enterDirectory: "フォルダーを開く",
    parentDirectory: "上の階層へ",
    contextRoot: "ワークスペースのルート",
    contextLoading: "リソースを読み込み中…",
    contextRetry: "再試行",
    tryResume: "再開を試す",
    modeUnknown: "ネイティブモードは未確認",
    nativeChanged:
      "Codex の状態が変わりました。下書きは保持されています。再読み込み後に送信してください。",
    reloadDraft: "再読み込み",
    nextTurn: "次のターン",
    settingsPending: "次のターンの選択を保存しました。送信後に Codex の状態で反映を確認します。",
    settingsUnknown: "設定の反映を確認中",
    done: "完了",
    selected: "選択済み",
    help: "送信について",
    queue: "キューのメッセージは現在のターン終了後に自動実行されます。",
    pending: "リクエストの結果を確認する必要があります。再送しないでください。",
    offline: "接続が切れました。再接続後に送信できます。",
    connecting: "会話の状態を確認しています…",
    readOnly: "この会話は閲覧のみです。送信は利用できません。",
    permission: "このブラウザーには送信権限がありません。",
    waiting: "保留中の承認または質問に先に対応してください。",
  },
} satisfies Record<Locale, Record<string, string>>;
export const composerLayoutCopy = copy;
const terms: Record<Locale, Record<string, string>> = {
  "zh-CN": {
    none: "无",
    minimal: "最低",
    low: "低",
    medium: "中",
    high: "高",
    xhigh: "更高",
    max: "最高",
    ultra: "极高",
    file: "文件",
    directory: "文件夹",
    skill: "技能",
    plugin: "插件",
    app: "应用",
    active: "进行中",
    paused: "已暂停",
    complete: "已完成",
    completed: "已完成",
    blocked: "受阻",
    budget_exhausted: "预算耗尽",
    budgetLimited: "预算受限",
    usageLimited: "用量受限",
  },
  "zh-TW": {
    none: "無",
    minimal: "最低",
    low: "低",
    medium: "中",
    high: "高",
    xhigh: "更高",
    max: "最高",
    ultra: "極高",
    file: "檔案",
    directory: "資料夾",
    skill: "技能",
    plugin: "外掛",
    app: "應用",
    active: "進行中",
    paused: "已暫停",
    complete: "已完成",
    completed: "已完成",
    blocked: "受阻",
    budget_exhausted: "預算耗盡",
    budgetLimited: "預算受限",
    usageLimited: "用量受限",
  },
  "en-US": {
    none: "None",
    minimal: "Minimal",
    low: "Low",
    medium: "Medium",
    high: "High",
    xhigh: "Extra high",
    max: "Maximum",
    ultra: "Ultra",
    file: "File",
    directory: "Folder",
    skill: "Skill",
    plugin: "Plugin",
    app: "App",
    active: "Active",
    paused: "Paused",
    complete: "Complete",
    completed: "Complete",
    blocked: "Blocked",
    budget_exhausted: "Budget exhausted",
    budgetLimited: "Budget limited",
    usageLimited: "Usage limited",
  },
  "ja-JP": {
    none: "なし",
    minimal: "最小",
    low: "低",
    medium: "中",
    high: "高",
    xhigh: "より高い",
    max: "最大",
    ultra: "最高",
    file: "ファイル",
    directory: "フォルダー",
    skill: "スキル",
    plugin: "プラグイン",
    app: "アプリ",
    active: "実行中",
    paused: "一時停止",
    complete: "完了",
    completed: "完了",
    blocked: "ブロック中",
    budget_exhausted: "予算上限",
    budgetLimited: "予算制限",
    usageLimited: "使用量制限",
  },
};
export function composerTerm(locale: Locale, term: string) {
  return terms[locale][term] ?? term;
}
