import type { Locale } from "../../i18n";

const zh = {
  actions: "会话操作",
  management: "会话管理",
  ownership: "执行归属",
  diagnostics: "诊断",
  files: "文件与产物",
  connecting: "连接中",
  offline: "已断线",
  uncertain: "结果待核对",
  approval: "待审批",
  question: "需要回答",
  running: "执行中",
  cancelled: "已取消",
  ready: "可发送",
  readonly: "仅可查看",
  verifying: "正在核对状态",
  busy: "正在提交",
  help: "使用说明",
  pending: "待处理",
  preferences: "外观与语言",
  newMessages: "有新消息，返回最新",
};
type Copy = { [K in keyof typeof zh]: string };
export const webLayoutCopy: Record<Locale, Copy> = {
  "zh-CN": zh,
  "zh-TW": {
    actions: "對話操作",
    management: "對話管理",
    ownership: "執行歸屬",
    diagnostics: "診斷",
    files: "檔案與產物",
    connecting: "連線中",
    offline: "已斷線",
    uncertain: "結果待核對",
    approval: "待審批",
    question: "需要回答",
    running: "執行中",
    cancelled: "已取消",
    ready: "可傳送",
    readonly: "僅可檢視",
    verifying: "正在核對狀態",
    busy: "正在提交",
    help: "使用說明",
    pending: "待處理",
    preferences: "外觀與語言",
    newMessages: "有新訊息，返回最新",
  },
  "en-US": {
    actions: "Session actions",
    management: "Session management",
    ownership: "Execution ownership",
    diagnostics: "Diagnostics",
    files: "Files & artifacts",
    connecting: "Connecting",
    offline: "Disconnected",
    uncertain: "Result unconfirmed",
    approval: "Approval needed",
    question: "Answer needed",
    running: "Running",
    cancelled: "Cancelled",
    ready: "Ready to send",
    readonly: "View only",
    verifying: "Verifying state",
    busy: "Submitting",
    help: "Help",
    pending: "Pending",
    preferences: "Appearance & language",
    newMessages: "New messages — jump to latest",
  },
  "ja-JP": {
    actions: "会話の操作",
    management: "会話の管理",
    ownership: "実行の所有者",
    diagnostics: "診断",
    files: "ファイルと成果物",
    connecting: "接続中",
    offline: "切断",
    uncertain: "結果の確認待ち",
    approval: "承認待ち",
    question: "回答が必要",
    running: "実行中",
    cancelled: "キャンセル済み",
    ready: "送信可能",
    readonly: "閲覧のみ",
    verifying: "状態を確認中",
    busy: "送信中",
    help: "使い方",
    pending: "対応待ち",
    preferences: "外観と言語",
    newMessages: "新しいメッセージ · 最新へ移動",
  },
};
